Include untracked changes aka new code files in patches
paranext/paranext pull request #25
Opened 2024-08-13 19:59 UTC by tjcouch-sil

2024-08-13 21:38 UTC, tombogle approved these changes

2024-08-14 00:02 UTC, irahopkinson requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext/25)* status: all files reviewed, 1 unresolved discussion (waiting on @tjcouch-sil)

___
*[`lib/git.util.ts` line 77 at r1](https://reviewable.io/reviews/paranext/paranext/25#-O4DAp1EE5ZiThujfWSp:-O4DAp1EE5ZiThujfWSq:b-fw8us1) ([raw file](https://github.com/paranext/paranext/blob/bfb6beecc12fe7dd4183b0d9d47e17d377e85fbb/lib/git.util.ts#L77)):*
> ```XML
>       // We want to run these one-at-a-time, so we're using for/of instead of .forEach
>       // eslint-disable-next-line no-await-in-loop
>       await execCommand('git add .', {
> ```

Hmm... won't this quietly blow away changes? That feels like a bad idea.


<!-- Sent from Reviewable.io -->

2024-08-14 13:54 UTC, tjcouch-sil reviewed
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext/25)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`lib/git.util.ts` line 77 at r1](https://reviewable.io/reviews/paranext/paranext/25#-O4DAp1EE5ZiThujfWSp:-O4G9juS78qWEIbdY5nQ:b-g9s9y1) ([raw file](https://github.com/paranext/paranext/blob/bfb6beecc12fe7dd4183b0d9d47e17d377e85fbb/lib/git.util.ts#L77)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Hmm... won't this quietly blow away changes? That feels like a bad idea.
</blockquote></details>

Yes. This was already doing that. You have to be careful using this repo :grimacing:


<!-- Sent from Reviewable.io -->

2024-08-14 19:07 UTC, irahopkinson approved these changes
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext/25)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-08-14 19:07 UTC, merged